### ISSUE TITLE
TypeError: object of type 'int' has no len() on get_all_responses

### ISSUE THREAD

**Issue by TheFoolInRed** [andrewkshim/surveymonty#7]
There is a good chance I'm doing this wrong as I'm a bit of a python noob, but here's what's going on. 
I'm trying to gather all the responses from one of my survey collectors. Here's my code

```
import surveymonty

access_token = "redacted"
api_key = "redacted"

api = surveymonty.Client(access_token, api_key)
surveylist = api.get_survey_list()

print(api.get_all_responses(59032175, 5034218963))
```

Output: Traceback (most recent call last):
  File "C:/Users/khales/PycharmProjects/surveymonkey export/surveymonkey export.py", line 19, in <module>
    print(api.get_all_responses(59032175, 5034218963))
  File "C:\Users\khales\AppData\Local\Programs\Python\Python35\lib\site-packages\surveymonty.py", line 416, in get_all_responses
    len(respondent_ids) / float(self.NUM_RESPONSES_PER_CALL)
TypeError: object of type 'int' has no len()

The first ID, 59032175 is the ID of the survey and the second (5034218963) is a specific respondent. Ideally I'd request all of them but I get them all but when I try to do 

```
x = api.get_respondent_list(59032175)
print(api.get_all_responses(59032175, x))
```

Output: Traceback (most recent call last):
  File "C:/Users/khales/PycharmProjects/surveymonkey export/surveymonkey export.py", line 19, in <module>
    print(api.get_all_responses(59032175, x))
  File "C:\Users\khales\AppData\Local\Programs\Python\Python35\lib\site-packages\surveymonty.py", line 421, in get_all_responses
    survey_id, respondent_ids, options, page_index
  File "C:\Users\khales\AppData\Local\Programs\Python\Python35\lib\site-packages\surveymonty.py", line 388, in get_responses
    in respondent_ids[start_index: end_index]
TypeError: unhashable type: 'slice'

Any idea what I might be doing wrong on this?

**Comment by andrewkshim** [comment]
Hey @TheFoolInRed, this is happening because the `get_all_responses` method expects the second argument to be a list: https://github.com/andrewkshim/surveymonty/blob/master/surveymonty.py#L368

This is completely the documentation's fault. I wrote this library a long time ago and haven't maintained it. I'll polish up the docs and code when I find some free time (or feel free to update the docs yourself and submit a PR).

But back to your issue, wraping the second argument in square brackets to make it a list should resolve the issue e.g.

```python
print(api.get_all_responses(59032175, [5034218963]))
```

**Comment by andrewkshim** [comment]
Closing this issue. With the [recent 0.2.5 release](https://github.com/andrewkshim/surveymonty/pull/9), I'm relying much more on the SurveyMonkey API docs to indicate what you should be passing into the client methods. If you're still using this project and have any questions about the new interface, feel free to reach out again.
