### ISSUE TITLE
SurveyMonkey v2 API no longer supported

### ISSUE THREAD

**Issue by tkooda** [andrewkshim/surveymonty#8]
SurveyMonkey has finally disabled v2 of their API.

All surveymonty calls to SurveyMonkey's v2 API fail with this error now:

`surveymonty.SurveyMontyAPIError: Status code 3 Invalid Request - Access to V2 of the API is no longer supported.`

**Comment by andrewkshim** [comment]
Hi @tkooda, thanks for pointing this out. I updated the lib and the client now supports the v3 API. I changed the client interface though, so take a look through [the updated README](https://github.com/andrewkshim/surveymonty/blob/master/README.md) if you're still interested in using the lib.
